spring:
  application:
    name: gateway-web
   #Redis配置
  redis:
    host: 192.168.43.220
    port: 6379
  cloud:
      gateway:
        globalcors: #全局配置
          cors-configurations:
            '[/**]': # 匹配所有请求
                allowedOrigins: "*" #跨域处理 允许所有的域
                allowedMethods: # 支持的方法
                  - GET
                  - POST
                  - PUT
                  - DELETE
        routes:
              - id: wxyj_goods_route
                #uri: http://localhost:18081
                #lb负载均衡，使用服务名负载均衡
                uri: lb://goods
                predicates:
                        #用户请求域名配置，所有以一下域名的请求都被   http://localhost:18081  处理
                        #- Host=cloud.itheima.com**
                        #所有以/brand开始的请求都交给  http://localhost:18081 处理
                - Path=/api/goods/**
                filters:
                  #- PrefixPath=/brand
                - StripPrefix=1
                - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 1

              - id: wxyj_user_route
                uri: lb://goods
                predicates:
                - Path=/api/user/**
                filters:
                - StripPrefix=1
                - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
                  args:
                    key-resolver: "#{@ipKeyResolver}"
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 1
                            #用户微服务
              - id: wxyj_user_route
                uri: lb://user
                predicates:
                - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
                filters:
                - StripPrefix=1


              - id: wxyj_order_route
                uri: lb://order
                predicates:
                - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
                filters:
                - StripPrefix=1

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true